// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import type { Effect, Stream } from "effect"
import type { HttpApiClient } from "effect/unstable/httpapi"
import type { ClientApi } from "../../contract"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>
type EffectValue<A> = A extends Effect.Effect<infer Success, any, any> ? Success : never
type StreamValue<A> = A extends Stream.Stream<infer Success, any, any> ? Success : never

export type Endpoint0_0Output = EffectValue<ReturnType<RawClient["server.health"]["health.get"]>>
export type HealthGetOperation<E = never> = () => Effect.Effect<Endpoint0_0Output, E>

type Endpoint0_1Request = Parameters<RawClient["server.health"]["health.stop"]>[0]
export type Endpoint0_1Input = {
  readonly instanceID: Endpoint0_1Request["payload"]["instanceID"]
  readonly targetVersion?: Endpoint0_1Request["payload"]["targetVersion"]
}
export type Endpoint0_1Output = EffectValue<ReturnType<RawClient["server.health"]["health.stop"]>>
export type HealthStopOperation<E = never> = (input: Endpoint0_1Input) => Effect.Effect<Endpoint0_1Output, E>

export interface HealthApi<E = never> {
  readonly get: HealthGetOperation<E>
  readonly stop: HealthStopOperation<E>
}

export type Endpoint1_0Output = EffectValue<ReturnType<RawClient["server.server"]["server.get"]>>
export type ServerGetOperation<E = never> = () => Effect.Effect<Endpoint1_0Output, E>

export interface ServerApi<E = never> {
  readonly get: ServerGetOperation<E>
}

export type Endpoint2_0Output = EffectValue<ReturnType<RawClient["server.pairing"]["pairing.invitation.create"]>>
export type PairingInvitationCreateOperation<E = never> = () => Effect.Effect<Endpoint2_0Output, E>

type Endpoint2_1Request = Parameters<RawClient["server.pairing"]["pairing.redeem"]>[0]
export type Endpoint2_1Input = {
  readonly token: Endpoint2_1Request["payload"]["token"]
  readonly requestID: Endpoint2_1Request["payload"]["requestID"]
  readonly deviceName: Endpoint2_1Request["payload"]["deviceName"]
  readonly credential: Endpoint2_1Request["payload"]["credential"]
}
export type Endpoint2_1Output = EffectValue<ReturnType<RawClient["server.pairing"]["pairing.redeem"]>>
export type PairingRedeemOperation<E = never> = (input: Endpoint2_1Input) => Effect.Effect<Endpoint2_1Output, E>

export type Endpoint2_2Output = EffectValue<ReturnType<RawClient["server.pairing"]["pairing.device.list"]>>
export type PairingDeviceListOperation<E = never> = () => Effect.Effect<Endpoint2_2Output, E>

type Endpoint2_3Request = Parameters<RawClient["server.pairing"]["pairing.device.revoke"]>[0]
export type Endpoint2_3Input = { readonly deviceID: Endpoint2_3Request["params"]["deviceID"] }
export type Endpoint2_3Output = EffectValue<ReturnType<RawClient["server.pairing"]["pairing.device.revoke"]>>
export type PairingDeviceRevokeOperation<E = never> = (input: Endpoint2_3Input) => Effect.Effect<Endpoint2_3Output, E>

export interface PairingApi<E = never> {
  readonly invitation: { readonly create: PairingInvitationCreateOperation<E> }
  readonly redeem: PairingRedeemOperation<E>
  readonly device: { readonly list: PairingDeviceListOperation<E>; readonly revoke: PairingDeviceRevokeOperation<E> }
}

type Endpoint3_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
export type Endpoint3_0Input = { readonly location?: Endpoint3_0Request["query"]["location"] }
export type Endpoint3_0Output = EffectValue<ReturnType<RawClient["server.location"]["location.get"]>>
export type LocationGetOperation<E = never> = (input?: Endpoint3_0Input) => Effect.Effect<Endpoint3_0Output, E>

export interface LocationApi<E = never> {
  readonly get: LocationGetOperation<E>
}

type Endpoint4_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
export type Endpoint4_0Input = { readonly location?: Endpoint4_0Request["query"]["location"] }
export type Endpoint4_0Output = EffectValue<ReturnType<RawClient["server.agent"]["agent.list"]>>
export type AgentListOperation<E = never> = (input?: Endpoint4_0Input) => Effect.Effect<Endpoint4_0Output, E>

export interface AgentApi<E = never> {
  readonly list: AgentListOperation<E>
}

type Endpoint5_0Request = Parameters<RawClient["server.plugin"]["plugin.list"]>[0]
export type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
export type Endpoint5_0Output = EffectValue<ReturnType<RawClient["server.plugin"]["plugin.list"]>>
export type PluginListOperation<E = never> = (input?: Endpoint5_0Input) => Effect.Effect<Endpoint5_0Output, E>

export interface PluginApi<E = never> {
  readonly list: PluginListOperation<E>
}

type Endpoint6_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
export type Endpoint6_0Input = {
  readonly workspace?: Endpoint6_0Request["query"]["workspace"]
  readonly limit?: Endpoint6_0Request["query"]["limit"]
  readonly order?: Endpoint6_0Request["query"]["order"]
  readonly search?: Endpoint6_0Request["query"]["search"]
  readonly parentID?: Endpoint6_0Request["query"]["parentID"]
  readonly directory?: Endpoint6_0Request["query"]["directory"]
  readonly project?: Endpoint6_0Request["query"]["project"]
  readonly subpath?: Endpoint6_0Request["query"]["subpath"]
  readonly cursor?: Endpoint6_0Request["query"]["cursor"]
}
export type Endpoint6_0Output = EffectValue<ReturnType<RawClient["server.session"]["session.list"]>>
export type SessionListOperation<E = never> = (input?: Endpoint6_0Input) => Effect.Effect<Endpoint6_0Output, E>

type Endpoint6_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
export type Endpoint6_1Input = {
  readonly id?: Endpoint6_1Request["payload"]["id"]
  readonly agent?: Endpoint6_1Request["payload"]["agent"]
  readonly model?: Endpoint6_1Request["payload"]["model"]
  readonly location?: Endpoint6_1Request["payload"]["location"]
}
export type Endpoint6_1Output = EffectValue<ReturnType<RawClient["server.session"]["session.create"]>>["data"]
export type SessionCreateOperation<E = never> = (input?: Endpoint6_1Input) => Effect.Effect<Endpoint6_1Output, E>

export type Endpoint6_2Output = EffectValue<ReturnType<RawClient["server.session"]["session.active"]>>["data"]
export type SessionActiveOperation<E = never> = () => Effect.Effect<Endpoint6_2Output, E>

type Endpoint6_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
export type Endpoint6_3Input = { readonly sessionID: Endpoint6_3Request["params"]["sessionID"] }
export type Endpoint6_3Output = EffectValue<ReturnType<RawClient["server.session"]["session.get"]>>["data"]
export type SessionGetOperation<E = never> = (input: Endpoint6_3Input) => Effect.Effect<Endpoint6_3Output, E>

type Endpoint6_4Request = Parameters<RawClient["server.session"]["session.remove"]>[0]
export type Endpoint6_4Input = { readonly sessionID: Endpoint6_4Request["params"]["sessionID"] }
export type Endpoint6_4Output = EffectValue<ReturnType<RawClient["server.session"]["session.remove"]>>
export type SessionRemoveOperation<E = never> = (input: Endpoint6_4Input) => Effect.Effect<Endpoint6_4Output, E>

type Endpoint6_5Request = Parameters<RawClient["server.session"]["session.fork"]>[0]
export type Endpoint6_5Input = {
  readonly sessionID: Endpoint6_5Request["params"]["sessionID"]
  readonly messageID?: Endpoint6_5Request["payload"]["messageID"]
}
export type Endpoint6_5Output = EffectValue<ReturnType<RawClient["server.session"]["session.fork"]>>["data"]
export type SessionForkOperation<E = never> = (input: Endpoint6_5Input) => Effect.Effect<Endpoint6_5Output, E>

type Endpoint6_6Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
export type Endpoint6_6Input = {
  readonly sessionID: Endpoint6_6Request["params"]["sessionID"]
  readonly agent: Endpoint6_6Request["payload"]["agent"]
}
export type Endpoint6_6Output = EffectValue<ReturnType<RawClient["server.session"]["session.switchAgent"]>>
export type SessionSwitchAgentOperation<E = never> = (input: Endpoint6_6Input) => Effect.Effect<Endpoint6_6Output, E>

type Endpoint6_7Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
export type Endpoint6_7Input = {
  readonly sessionID: Endpoint6_7Request["params"]["sessionID"]
  readonly model: Endpoint6_7Request["payload"]["model"]
}
export type Endpoint6_7Output = EffectValue<ReturnType<RawClient["server.session"]["session.switchModel"]>>
export type SessionSwitchModelOperation<E = never> = (input: Endpoint6_7Input) => Effect.Effect<Endpoint6_7Output, E>

type Endpoint6_8Request = Parameters<RawClient["server.session"]["session.rename"]>[0]
export type Endpoint6_8Input = {
  readonly sessionID: Endpoint6_8Request["params"]["sessionID"]
  readonly title: Endpoint6_8Request["payload"]["title"]
}
export type Endpoint6_8Output = EffectValue<ReturnType<RawClient["server.session"]["session.rename"]>>
export type SessionRenameOperation<E = never> = (input: Endpoint6_8Input) => Effect.Effect<Endpoint6_8Output, E>

type Endpoint6_9Request = Parameters<RawClient["server.session"]["session.move"]>[0]
export type Endpoint6_9Input = {
  readonly sessionID: Endpoint6_9Request["params"]["sessionID"]
  readonly directory: Endpoint6_9Request["payload"]["directory"]
  readonly workspaceID?: Endpoint6_9Request["payload"]["workspaceID"]
}
export type Endpoint6_9Output = EffectValue<ReturnType<RawClient["server.session"]["session.move"]>>
export type SessionMoveOperation<E = never> = (input: Endpoint6_9Input) => Effect.Effect<Endpoint6_9Output, E>

type Endpoint6_10Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
export type Endpoint6_10Input = {
  readonly sessionID: Endpoint6_10Request["params"]["sessionID"]
  readonly id?: Endpoint6_10Request["payload"]["id"]
  readonly text: Endpoint6_10Request["payload"]["text"]
  readonly files?: Endpoint6_10Request["payload"]["files"]
  readonly agents?: Endpoint6_10Request["payload"]["agents"]
  readonly metadata?: Endpoint6_10Request["payload"]["metadata"]
  readonly delivery?: Endpoint6_10Request["payload"]["delivery"]
  readonly resume?: Endpoint6_10Request["payload"]["resume"]
}
export type Endpoint6_10Output = EffectValue<ReturnType<RawClient["server.session"]["session.prompt"]>>["data"]
export type SessionPromptOperation<E = never> = (input: Endpoint6_10Input) => Effect.Effect<Endpoint6_10Output, E>

type Endpoint6_11Request = Parameters<RawClient["server.session"]["session.command"]>[0]
export type Endpoint6_11Input = {
  readonly sessionID: Endpoint6_11Request["params"]["sessionID"]
  readonly id?: Endpoint6_11Request["payload"]["id"]
  readonly command: Endpoint6_11Request["payload"]["command"]
  readonly arguments?: Endpoint6_11Request["payload"]["arguments"]
  readonly agent?: Endpoint6_11Request["payload"]["agent"]
  readonly model?: Endpoint6_11Request["payload"]["model"]
  readonly files?: Endpoint6_11Request["payload"]["files"]
  readonly agents?: Endpoint6_11Request["payload"]["agents"]
  readonly delivery?: Endpoint6_11Request["payload"]["delivery"]
  readonly resume?: Endpoint6_11Request["payload"]["resume"]
}
export type Endpoint6_11Output = EffectValue<ReturnType<RawClient["server.session"]["session.command"]>>["data"]
export type SessionCommandOperation<E = never> = (input: Endpoint6_11Input) => Effect.Effect<Endpoint6_11Output, E>

type Endpoint6_12Request = Parameters<RawClient["server.session"]["session.skill"]>[0]
export type Endpoint6_12Input = {
  readonly sessionID: Endpoint6_12Request["params"]["sessionID"]
  readonly id?: Endpoint6_12Request["payload"]["id"]
  readonly skill: Endpoint6_12Request["payload"]["skill"]
  readonly resume?: Endpoint6_12Request["payload"]["resume"]
}
export type Endpoint6_12Output = EffectValue<ReturnType<RawClient["server.session"]["session.skill"]>>
export type SessionSkillOperation<E = never> = (input: Endpoint6_12Input) => Effect.Effect<Endpoint6_12Output, E>

type Endpoint6_13Request = Parameters<RawClient["server.session"]["session.synthetic"]>[0]
export type Endpoint6_13Input = {
  readonly sessionID: Endpoint6_13Request["params"]["sessionID"]
  readonly id?: Endpoint6_13Request["payload"]["id"]
  readonly text: Endpoint6_13Request["payload"]["text"]
  readonly description?: Endpoint6_13Request["payload"]["description"]
  readonly metadata?: Endpoint6_13Request["payload"]["metadata"]
  readonly delivery?: Endpoint6_13Request["payload"]["delivery"]
  readonly resume?: Endpoint6_13Request["payload"]["resume"]
}
export type Endpoint6_13Output = EffectValue<ReturnType<RawClient["server.session"]["session.synthetic"]>>["data"]
export type SessionSyntheticOperation<E = never> = (input: Endpoint6_13Input) => Effect.Effect<Endpoint6_13Output, E>

type Endpoint6_14Request = Parameters<RawClient["server.session"]["session.shell"]>[0]
export type Endpoint6_14Input = {
  readonly sessionID: Endpoint6_14Request["params"]["sessionID"]
  readonly id?: Endpoint6_14Request["payload"]["id"]
  readonly command: Endpoint6_14Request["payload"]["command"]
}
export type Endpoint6_14Output = EffectValue<ReturnType<RawClient["server.session"]["session.shell"]>>
export type SessionShellOperation<E = never> = (input: Endpoint6_14Input) => Effect.Effect<Endpoint6_14Output, E>

type Endpoint6_15Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
export type Endpoint6_15Input = {
  readonly sessionID: Endpoint6_15Request["params"]["sessionID"]
  readonly id?: Endpoint6_15Request["payload"]["id"]
}
export type Endpoint6_15Output = EffectValue<ReturnType<RawClient["server.session"]["session.compact"]>>["data"]
export type SessionCompactOperation<E = never> = (input: Endpoint6_15Input) => Effect.Effect<Endpoint6_15Output, E>

type Endpoint6_16Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
export type Endpoint6_16Input = { readonly sessionID: Endpoint6_16Request["params"]["sessionID"] }
export type Endpoint6_16Output = EffectValue<ReturnType<RawClient["server.session"]["session.wait"]>>
export type SessionWaitOperation<E = never> = (input: Endpoint6_16Input) => Effect.Effect<Endpoint6_16Output, E>

type Endpoint6_17Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
export type Endpoint6_17Input = {
  readonly sessionID: Endpoint6_17Request["params"]["sessionID"]
  readonly messageID: Endpoint6_17Request["payload"]["messageID"]
  readonly files?: Endpoint6_17Request["payload"]["files"]
}
export type Endpoint6_17Output = EffectValue<ReturnType<RawClient["server.session"]["session.revert.stage"]>>["data"]
export type SessionRevertStageOperation<E = never> = (input: Endpoint6_17Input) => Effect.Effect<Endpoint6_17Output, E>

type Endpoint6_18Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
export type Endpoint6_18Input = { readonly sessionID: Endpoint6_18Request["params"]["sessionID"] }
export type Endpoint6_18Output = EffectValue<ReturnType<RawClient["server.session"]["session.revert.clear"]>>
export type SessionRevertClearOperation<E = never> = (input: Endpoint6_18Input) => Effect.Effect<Endpoint6_18Output, E>

type Endpoint6_19Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
export type Endpoint6_19Input = { readonly sessionID: Endpoint6_19Request["params"]["sessionID"] }
export type Endpoint6_19Output = EffectValue<ReturnType<RawClient["server.session"]["session.revert.commit"]>>
export type SessionRevertCommitOperation<E = never> = (input: Endpoint6_19Input) => Effect.Effect<Endpoint6_19Output, E>

type Endpoint6_20Request = Parameters<RawClient["server.session"]["session.context"]>[0]
export type Endpoint6_20Input = { readonly sessionID: Endpoint6_20Request["params"]["sessionID"] }
export type Endpoint6_20Output = EffectValue<ReturnType<RawClient["server.session"]["session.context"]>>["data"]
export type SessionContextOperation<E = never> = (input: Endpoint6_20Input) => Effect.Effect<Endpoint6_20Output, E>

type Endpoint6_21Request = Parameters<RawClient["server.session"]["session.pending.list"]>[0]
export type Endpoint6_21Input = { readonly sessionID: Endpoint6_21Request["params"]["sessionID"] }
export type Endpoint6_21Output = EffectValue<ReturnType<RawClient["server.session"]["session.pending.list"]>>["data"]
export type SessionPendingListOperation<E = never> = (input: Endpoint6_21Input) => Effect.Effect<Endpoint6_21Output, E>

type Endpoint6_22Request = Parameters<RawClient["server.session"]["session.instructions.entry.list"]>[0]
export type Endpoint6_22Input = { readonly sessionID: Endpoint6_22Request["params"]["sessionID"] }
export type Endpoint6_22Output = EffectValue<
  ReturnType<RawClient["server.session"]["session.instructions.entry.list"]>
>["data"]
export type SessionInstructionsEntryListOperation<E = never> = (
  input: Endpoint6_22Input,
) => Effect.Effect<Endpoint6_22Output, E>

type Endpoint6_23Request = Parameters<RawClient["server.session"]["session.instructions.entry.put"]>[0]
export type Endpoint6_23Input = {
  readonly sessionID: Endpoint6_23Request["params"]["sessionID"]
  readonly key: Endpoint6_23Request["params"]["key"]
  readonly value: Endpoint6_23Request["payload"]["value"]
}
export type Endpoint6_23Output = EffectValue<ReturnType<RawClient["server.session"]["session.instructions.entry.put"]>>
export type SessionInstructionsEntryPutOperation<E = never> = (
  input: Endpoint6_23Input,
) => Effect.Effect<Endpoint6_23Output, E>

type Endpoint6_24Request = Parameters<RawClient["server.session"]["session.instructions.entry.remove"]>[0]
export type Endpoint6_24Input = {
  readonly sessionID: Endpoint6_24Request["params"]["sessionID"]
  readonly key: Endpoint6_24Request["params"]["key"]
}
export type Endpoint6_24Output = EffectValue<
  ReturnType<RawClient["server.session"]["session.instructions.entry.remove"]>
>
export type SessionInstructionsEntryRemoveOperation<E = never> = (
  input: Endpoint6_24Input,
) => Effect.Effect<Endpoint6_24Output, E>

type Endpoint6_25Request = Parameters<RawClient["server.session"]["session.log"]>[0]
export type Endpoint6_25Input = {
  readonly sessionID: Endpoint6_25Request["params"]["sessionID"]
  readonly after?: Endpoint6_25Request["query"]["after"]
  readonly follow?: Endpoint6_25Request["query"]["follow"]
}
export type Endpoint6_25Output = StreamValue<EffectValue<ReturnType<RawClient["server.session"]["session.log"]>>>
export type SessionLogOperation<E = never> = (input: Endpoint6_25Input) => Stream.Stream<Endpoint6_25Output, E>

type Endpoint6_26Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
export type Endpoint6_26Input = { readonly sessionID: Endpoint6_26Request["params"]["sessionID"] }
export type Endpoint6_26Output = EffectValue<ReturnType<RawClient["server.session"]["session.interrupt"]>>
export type SessionInterruptOperation<E = never> = (input: Endpoint6_26Input) => Effect.Effect<Endpoint6_26Output, E>

type Endpoint6_27Request = Parameters<RawClient["server.session"]["session.background"]>[0]
export type Endpoint6_27Input = { readonly sessionID: Endpoint6_27Request["params"]["sessionID"] }
export type Endpoint6_27Output = EffectValue<ReturnType<RawClient["server.session"]["session.background"]>>
export type SessionBackgroundOperation<E = never> = (input: Endpoint6_27Input) => Effect.Effect<Endpoint6_27Output, E>

type Endpoint6_28Request = Parameters<RawClient["server.session"]["session.message"]>[0]
export type Endpoint6_28Input = {
  readonly sessionID: Endpoint6_28Request["params"]["sessionID"]
  readonly messageID: Endpoint6_28Request["params"]["messageID"]
}
export type Endpoint6_28Output = EffectValue<ReturnType<RawClient["server.session"]["session.message"]>>["data"]
export type SessionMessageOperation<E = never> = (input: Endpoint6_28Input) => Effect.Effect<Endpoint6_28Output, E>

export interface SessionApi<E = never> {
  readonly list: SessionListOperation<E>
  readonly create: SessionCreateOperation<E>
  readonly active: SessionActiveOperation<E>
  readonly get: SessionGetOperation<E>
  readonly remove: SessionRemoveOperation<E>
  readonly fork: SessionForkOperation<E>
  readonly switchAgent: SessionSwitchAgentOperation<E>
  readonly switchModel: SessionSwitchModelOperation<E>
  readonly rename: SessionRenameOperation<E>
  readonly move: SessionMoveOperation<E>
  readonly prompt: SessionPromptOperation<E>
  readonly command: SessionCommandOperation<E>
  readonly skill: SessionSkillOperation<E>
  readonly synthetic: SessionSyntheticOperation<E>
  readonly shell: SessionShellOperation<E>
  readonly compact: SessionCompactOperation<E>
  readonly wait: SessionWaitOperation<E>
  readonly revert: {
    readonly stage: SessionRevertStageOperation<E>
    readonly clear: SessionRevertClearOperation<E>
    readonly commit: SessionRevertCommitOperation<E>
  }
  readonly context: SessionContextOperation<E>
  readonly pending: { readonly list: SessionPendingListOperation<E> }
  readonly instructions: {
    readonly entry: {
      readonly list: SessionInstructionsEntryListOperation<E>
      readonly put: SessionInstructionsEntryPutOperation<E>
      readonly remove: SessionInstructionsEntryRemoveOperation<E>
    }
  }
  readonly log: SessionLogOperation<E>
  readonly interrupt: SessionInterruptOperation<E>
  readonly background: SessionBackgroundOperation<E>
  readonly message: SessionMessageOperation<E>
}

type Endpoint7_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
export type Endpoint7_0Input = {
  readonly sessionID: Endpoint7_0Request["params"]["sessionID"]
  readonly limit?: Endpoint7_0Request["query"]["limit"]
  readonly order?: Endpoint7_0Request["query"]["order"]
  readonly cursor?: Endpoint7_0Request["query"]["cursor"]
}
export type Endpoint7_0Output = EffectValue<ReturnType<RawClient["server.message"]["session.messages"]>>
export type MessageListOperation<E = never> = (input: Endpoint7_0Input) => Effect.Effect<Endpoint7_0Output, E>

export interface MessageApi<E = never> {
  readonly list: MessageListOperation<E>
}

type Endpoint8_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
export type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
export type Endpoint8_0Output = EffectValue<ReturnType<RawClient["server.model"]["model.list"]>>
export type ModelListOperation<E = never> = (input?: Endpoint8_0Input) => Effect.Effect<Endpoint8_0Output, E>

type Endpoint8_1Request = Parameters<RawClient["server.model"]["model.default"]>[0]
export type Endpoint8_1Input = { readonly location?: Endpoint8_1Request["query"]["location"] }
export type Endpoint8_1Output = EffectValue<ReturnType<RawClient["server.model"]["model.default"]>>
export type ModelDefaultOperation<E = never> = (input?: Endpoint8_1Input) => Effect.Effect<Endpoint8_1Output, E>

export interface ModelApi<E = never> {
  readonly list: ModelListOperation<E>
  readonly default: ModelDefaultOperation<E>
}

type Endpoint9_0Request = Parameters<RawClient["server.generate"]["generate.text"]>[0]
export type Endpoint9_0Input = {
  readonly location?: Endpoint9_0Request["query"]["location"]
  readonly prompt: Endpoint9_0Request["payload"]["prompt"]
  readonly model?: Endpoint9_0Request["payload"]["model"]
}
export type Endpoint9_0Output = EffectValue<ReturnType<RawClient["server.generate"]["generate.text"]>>["data"]
export type GenerateTextOperation<E = never> = (input: Endpoint9_0Input) => Effect.Effect<Endpoint9_0Output, E>

export interface GenerateApi<E = never> {
  readonly text: GenerateTextOperation<E>
}

type Endpoint10_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
export type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
export type Endpoint10_0Output = EffectValue<ReturnType<RawClient["server.provider"]["provider.list"]>>
export type ProviderListOperation<E = never> = (input?: Endpoint10_0Input) => Effect.Effect<Endpoint10_0Output, E>

type Endpoint10_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
export type Endpoint10_1Input = {
  readonly providerID: Endpoint10_1Request["params"]["providerID"]
  readonly location?: Endpoint10_1Request["query"]["location"]
}
export type Endpoint10_1Output = EffectValue<ReturnType<RawClient["server.provider"]["provider.get"]>>
export type ProviderGetOperation<E = never> = (input: Endpoint10_1Input) => Effect.Effect<Endpoint10_1Output, E>

export interface ProviderApi<E = never> {
  readonly list: ProviderListOperation<E>
  readonly get: ProviderGetOperation<E>
}

type Endpoint11_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
export type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
export type Endpoint11_0Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.list"]>>
export type IntegrationListOperation<E = never> = (input?: Endpoint11_0Input) => Effect.Effect<Endpoint11_0Output, E>

type Endpoint11_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
export type Endpoint11_1Input = {
  readonly integrationID: Endpoint11_1Request["params"]["integrationID"]
  readonly location?: Endpoint11_1Request["query"]["location"]
}
export type Endpoint11_1Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.get"]>>
export type IntegrationGetOperation<E = never> = (input: Endpoint11_1Input) => Effect.Effect<Endpoint11_1Output, E>

type Endpoint11_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
export type Endpoint11_2Input = {
  readonly integrationID: Endpoint11_2Request["params"]["integrationID"]
  readonly location?: Endpoint11_2Request["query"]["location"]
  readonly key: Endpoint11_2Request["payload"]["key"]
  readonly label?: Endpoint11_2Request["payload"]["label"]
}
export type Endpoint11_2Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.connect.key"]>>
export type IntegrationConnectKeyOperation<E = never> = (
  input: Endpoint11_2Input,
) => Effect.Effect<Endpoint11_2Output, E>

type Endpoint11_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
export type Endpoint11_3Input = {
  readonly integrationID: Endpoint11_3Request["params"]["integrationID"]
  readonly location?: Endpoint11_3Request["query"]["location"]
  readonly methodID: Endpoint11_3Request["payload"]["methodID"]
  readonly inputs: Endpoint11_3Request["payload"]["inputs"]
  readonly label?: Endpoint11_3Request["payload"]["label"]
}
export type Endpoint11_3Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.connect.oauth"]>>
export type IntegrationConnectOauthOperation<E = never> = (
  input: Endpoint11_3Input,
) => Effect.Effect<Endpoint11_3Output, E>

type Endpoint11_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
export type Endpoint11_4Input = {
  readonly attemptID: Endpoint11_4Request["params"]["attemptID"]
  readonly location?: Endpoint11_4Request["query"]["location"]
}
export type Endpoint11_4Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.attempt.status"]>>
export type IntegrationAttemptStatusOperation<E = never> = (
  input: Endpoint11_4Input,
) => Effect.Effect<Endpoint11_4Output, E>

type Endpoint11_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
export type Endpoint11_5Input = {
  readonly attemptID: Endpoint11_5Request["params"]["attemptID"]
  readonly location?: Endpoint11_5Request["query"]["location"]
  readonly code?: Endpoint11_5Request["payload"]["code"]
}
export type Endpoint11_5Output = EffectValue<
  ReturnType<RawClient["server.integration"]["integration.attempt.complete"]>
>
export type IntegrationAttemptCompleteOperation<E = never> = (
  input: Endpoint11_5Input,
) => Effect.Effect<Endpoint11_5Output, E>

type Endpoint11_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
export type Endpoint11_6Input = {
  readonly attemptID: Endpoint11_6Request["params"]["attemptID"]
  readonly location?: Endpoint11_6Request["query"]["location"]
}
export type Endpoint11_6Output = EffectValue<ReturnType<RawClient["server.integration"]["integration.attempt.cancel"]>>
export type IntegrationAttemptCancelOperation<E = never> = (
  input: Endpoint11_6Input,
) => Effect.Effect<Endpoint11_6Output, E>

export interface IntegrationApi<E = never> {
  readonly list: IntegrationListOperation<E>
  readonly get: IntegrationGetOperation<E>
  readonly connect: {
    readonly key: IntegrationConnectKeyOperation<E>
    readonly oauth: IntegrationConnectOauthOperation<E>
  }
  readonly attempt: {
    readonly status: IntegrationAttemptStatusOperation<E>
    readonly complete: IntegrationAttemptCompleteOperation<E>
    readonly cancel: IntegrationAttemptCancelOperation<E>
  }
}

type Endpoint12_0Request = Parameters<RawClient["server.mcp"]["mcp.list"]>[0]
export type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
export type Endpoint12_0Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.list"]>>
export type McpListOperation<E = never> = (input?: Endpoint12_0Input) => Effect.Effect<Endpoint12_0Output, E>

type Endpoint12_1Request = Parameters<RawClient["server.mcp"]["mcp.resource.catalog"]>[0]
export type Endpoint12_1Input = { readonly location?: Endpoint12_1Request["query"]["location"] }
export type Endpoint12_1Output = EffectValue<ReturnType<RawClient["server.mcp"]["mcp.resource.catalog"]>>
export type McpResourceCatalogOperation<E = never> = (input?: Endpoint12_1Input) => Effect.Effect<Endpoint12_1Output, E>

export interface McpApi<E = never> {
  readonly list: McpListOperation<E>
  readonly resource: { readonly catalog: McpResourceCatalogOperation<E> }
}

type Endpoint13_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
export type Endpoint13_0Input = {
  readonly credentialID: Endpoint13_0Request["params"]["credentialID"]
  readonly location?: Endpoint13_0Request["query"]["location"]
  readonly label: Endpoint13_0Request["payload"]["label"]
}
export type Endpoint13_0Output = EffectValue<ReturnType<RawClient["server.credential"]["credential.update"]>>
export type CredentialUpdateOperation<E = never> = (input: Endpoint13_0Input) => Effect.Effect<Endpoint13_0Output, E>

type Endpoint13_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
export type Endpoint13_1Input = {
  readonly credentialID: Endpoint13_1Request["params"]["credentialID"]
  readonly location?: Endpoint13_1Request["query"]["location"]
}
export type Endpoint13_1Output = EffectValue<ReturnType<RawClient["server.credential"]["credential.remove"]>>
export type CredentialRemoveOperation<E = never> = (input: Endpoint13_1Input) => Effect.Effect<Endpoint13_1Output, E>

export interface CredentialApi<E = never> {
  readonly update: CredentialUpdateOperation<E>
  readonly remove: CredentialRemoveOperation<E>
}

export type Endpoint14_0Output = EffectValue<ReturnType<RawClient["server.project"]["project.list"]>>
export type ProjectListOperation<E = never> = () => Effect.Effect<Endpoint14_0Output, E>

type Endpoint14_1Request = Parameters<RawClient["server.project"]["project.current"]>[0]
export type Endpoint14_1Input = { readonly location?: Endpoint14_1Request["query"]["location"] }
export type Endpoint14_1Output = EffectValue<ReturnType<RawClient["server.project"]["project.current"]>>
export type ProjectCurrentOperation<E = never> = (input?: Endpoint14_1Input) => Effect.Effect<Endpoint14_1Output, E>

type Endpoint14_2Request = Parameters<RawClient["server.project"]["project.directories"]>[0]
export type Endpoint14_2Input = {
  readonly projectID: Endpoint14_2Request["params"]["projectID"]
  readonly location?: Endpoint14_2Request["query"]["location"]
}
export type Endpoint14_2Output = EffectValue<ReturnType<RawClient["server.project"]["project.directories"]>>
export type ProjectDirectoriesOperation<E = never> = (input: Endpoint14_2Input) => Effect.Effect<Endpoint14_2Output, E>

export interface ProjectApi<E = never> {
  readonly list: ProjectListOperation<E>
  readonly current: ProjectCurrentOperation<E>
  readonly directories: ProjectDirectoriesOperation<E>
}

type Endpoint15_0Request = Parameters<RawClient["server.form"]["form.request.list"]>[0]
export type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
export type Endpoint15_0Output = EffectValue<ReturnType<RawClient["server.form"]["form.request.list"]>>
export type FormRequestListOperation<E = never> = (input?: Endpoint15_0Input) => Effect.Effect<Endpoint15_0Output, E>

type Endpoint15_1Request = Parameters<RawClient["server.form"]["session.form.list"]>[0]
export type Endpoint15_1Input = { readonly sessionID: Endpoint15_1Request["params"]["sessionID"] }
export type Endpoint15_1Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.list"]>>["data"]
export type FormListOperation<E = never> = (input: Endpoint15_1Input) => Effect.Effect<Endpoint15_1Output, E>

type Endpoint15_2Request = Parameters<RawClient["server.form"]["session.form.create"]>[0]
export type Endpoint15_2Input = {
  readonly sessionID: Endpoint15_2Request["params"]["sessionID"]
  readonly id?: Endpoint15_2Request["payload"]["id"]
  readonly title: Endpoint15_2Request["payload"]["title"]
  readonly metadata?: Endpoint15_2Request["payload"]["metadata"]
  readonly fields: Endpoint15_2Request["payload"]["fields"]
}
export type Endpoint15_2Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.create"]>>["data"]
export type FormCreateOperation<E = never> = (input: Endpoint15_2Input) => Effect.Effect<Endpoint15_2Output, E>

type Endpoint15_3Request = Parameters<RawClient["server.form"]["session.form.get"]>[0]
export type Endpoint15_3Input = {
  readonly sessionID: Endpoint15_3Request["params"]["sessionID"]
  readonly formID: Endpoint15_3Request["params"]["formID"]
}
export type Endpoint15_3Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.get"]>>["data"]
export type FormGetOperation<E = never> = (input: Endpoint15_3Input) => Effect.Effect<Endpoint15_3Output, E>

type Endpoint15_4Request = Parameters<RawClient["server.form"]["session.form.state"]>[0]
export type Endpoint15_4Input = {
  readonly sessionID: Endpoint15_4Request["params"]["sessionID"]
  readonly formID: Endpoint15_4Request["params"]["formID"]
}
export type Endpoint15_4Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.state"]>>["data"]
export type FormStateOperation<E = never> = (input: Endpoint15_4Input) => Effect.Effect<Endpoint15_4Output, E>

type Endpoint15_5Request = Parameters<RawClient["server.form"]["session.form.reply"]>[0]
export type Endpoint15_5Input = {
  readonly sessionID: Endpoint15_5Request["params"]["sessionID"]
  readonly formID: Endpoint15_5Request["params"]["formID"]
  readonly answer: Endpoint15_5Request["payload"]["answer"]
}
export type Endpoint15_5Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.reply"]>>
export type FormReplyOperation<E = never> = (input: Endpoint15_5Input) => Effect.Effect<Endpoint15_5Output, E>

type Endpoint15_6Request = Parameters<RawClient["server.form"]["session.form.cancel"]>[0]
export type Endpoint15_6Input = {
  readonly sessionID: Endpoint15_6Request["params"]["sessionID"]
  readonly formID: Endpoint15_6Request["params"]["formID"]
}
export type Endpoint15_6Output = EffectValue<ReturnType<RawClient["server.form"]["session.form.cancel"]>>
export type FormCancelOperation<E = never> = (input: Endpoint15_6Input) => Effect.Effect<Endpoint15_6Output, E>

export interface FormApi<E = never> {
  readonly request: { readonly list: FormRequestListOperation<E> }
  readonly list: FormListOperation<E>
  readonly create: FormCreateOperation<E>
  readonly get: FormGetOperation<E>
  readonly state: FormStateOperation<E>
  readonly reply: FormReplyOperation<E>
  readonly cancel: FormCancelOperation<E>
}

type Endpoint16_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
export type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
export type Endpoint16_0Output = EffectValue<ReturnType<RawClient["server.permission"]["permission.request.list"]>>
export type PermissionRequestListOperation<E = never> = (
  input?: Endpoint16_0Input,
) => Effect.Effect<Endpoint16_0Output, E>

type Endpoint16_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
export type Endpoint16_1Input = { readonly projectID?: Endpoint16_1Request["query"]["projectID"] }
export type Endpoint16_1Output = EffectValue<
  ReturnType<RawClient["server.permission"]["permission.saved.list"]>
>["data"]
export type PermissionSavedListOperation<E = never> = (
  input?: Endpoint16_1Input,
) => Effect.Effect<Endpoint16_1Output, E>

type Endpoint16_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
export type Endpoint16_2Input = { readonly id: Endpoint16_2Request["params"]["id"] }
export type Endpoint16_2Output = EffectValue<ReturnType<RawClient["server.permission"]["permission.saved.remove"]>>
export type PermissionSavedRemoveOperation<E = never> = (
  input: Endpoint16_2Input,
) => Effect.Effect<Endpoint16_2Output, E>

type Endpoint16_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
export type Endpoint16_3Input = {
  readonly sessionID: Endpoint16_3Request["params"]["sessionID"]
  readonly id?: Endpoint16_3Request["payload"]["id"]
  readonly action: Endpoint16_3Request["payload"]["action"]
  readonly resources: Endpoint16_3Request["payload"]["resources"]
  readonly save?: Endpoint16_3Request["payload"]["save"]
  readonly metadata?: Endpoint16_3Request["payload"]["metadata"]
  readonly source?: Endpoint16_3Request["payload"]["source"]
  readonly agent?: Endpoint16_3Request["payload"]["agent"]
}
export type Endpoint16_3Output = EffectValue<
  ReturnType<RawClient["server.permission"]["session.permission.create"]>
>["data"]
export type PermissionCreateOperation<E = never> = (input: Endpoint16_3Input) => Effect.Effect<Endpoint16_3Output, E>

type Endpoint16_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
export type Endpoint16_4Input = { readonly sessionID: Endpoint16_4Request["params"]["sessionID"] }
export type Endpoint16_4Output = EffectValue<
  ReturnType<RawClient["server.permission"]["session.permission.list"]>
>["data"]
export type PermissionListOperation<E = never> = (input: Endpoint16_4Input) => Effect.Effect<Endpoint16_4Output, E>

type Endpoint16_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
export type Endpoint16_5Input = {
  readonly sessionID: Endpoint16_5Request["params"]["sessionID"]
  readonly requestID: Endpoint16_5Request["params"]["requestID"]
}
export type Endpoint16_5Output = EffectValue<
  ReturnType<RawClient["server.permission"]["session.permission.get"]>
>["data"]
export type PermissionGetOperation<E = never> = (input: Endpoint16_5Input) => Effect.Effect<Endpoint16_5Output, E>

type Endpoint16_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
export type Endpoint16_6Input = {
  readonly sessionID: Endpoint16_6Request["params"]["sessionID"]
  readonly requestID: Endpoint16_6Request["params"]["requestID"]
  readonly reply: Endpoint16_6Request["payload"]["reply"]
  readonly message?: Endpoint16_6Request["payload"]["message"]
}
export type Endpoint16_6Output = EffectValue<ReturnType<RawClient["server.permission"]["session.permission.reply"]>>
export type PermissionReplyOperation<E = never> = (input: Endpoint16_6Input) => Effect.Effect<Endpoint16_6Output, E>

export interface PermissionApi<E = never> {
  readonly request: { readonly list: PermissionRequestListOperation<E> }
  readonly saved: { readonly list: PermissionSavedListOperation<E>; readonly remove: PermissionSavedRemoveOperation<E> }
  readonly create: PermissionCreateOperation<E>
  readonly list: PermissionListOperation<E>
  readonly get: PermissionGetOperation<E>
  readonly reply: PermissionReplyOperation<E>
}

type Endpoint17_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
export type Endpoint17_0Input = {
  readonly location?: Endpoint17_0Request["query"]["location"]
  readonly path?: Endpoint17_0Request["query"]["path"]
}
export type Endpoint17_0Output = EffectValue<ReturnType<RawClient["server.fs"]["fs.list"]>>
export type FileListOperation<E = never> = (input?: Endpoint17_0Input) => Effect.Effect<Endpoint17_0Output, E>

type Endpoint17_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
export type Endpoint17_1Input = {
  readonly location?: Endpoint17_1Request["query"]["location"]
  readonly query: Endpoint17_1Request["query"]["query"]
  readonly type?: Endpoint17_1Request["query"]["type"]
  readonly limit?: Endpoint17_1Request["query"]["limit"]
}
export type Endpoint17_1Output = EffectValue<ReturnType<RawClient["server.fs"]["fs.find"]>>
export type FileFindOperation<E = never> = (input: Endpoint17_1Input) => Effect.Effect<Endpoint17_1Output, E>

export interface FileApi<E = never> {
  readonly list: FileListOperation<E>
  readonly find: FileFindOperation<E>
}

type Endpoint18_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
export type Endpoint18_0Input = { readonly location?: Endpoint18_0Request["query"]["location"] }
export type Endpoint18_0Output = EffectValue<ReturnType<RawClient["server.command"]["command.list"]>>
export type CommandListOperation<E = never> = (input?: Endpoint18_0Input) => Effect.Effect<Endpoint18_0Output, E>

export interface CommandApi<E = never> {
  readonly list: CommandListOperation<E>
}

type Endpoint19_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
export type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
export type Endpoint19_0Output = EffectValue<ReturnType<RawClient["server.skill"]["skill.list"]>>
export type SkillListOperation<E = never> = (input?: Endpoint19_0Input) => Effect.Effect<Endpoint19_0Output, E>

export interface SkillApi<E = never> {
  readonly list: SkillListOperation<E>
}

export type Endpoint20_0Output = StreamValue<EffectValue<ReturnType<RawClient["server.event"]["event.subscribe"]>>>
export type EventSubscribeOperation<E = never> = () => Stream.Stream<Endpoint20_0Output, E>

export interface EventApi<E = never> {
  readonly subscribe: EventSubscribeOperation<E>
}

type Endpoint21_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
export type Endpoint21_0Input = { readonly location?: Endpoint21_0Request["query"]["location"] }
export type Endpoint21_0Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.list"]>>
export type PtyListOperation<E = never> = (input?: Endpoint21_0Input) => Effect.Effect<Endpoint21_0Output, E>

type Endpoint21_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
export type Endpoint21_1Input = {
  readonly location?: Endpoint21_1Request["query"]["location"]
  readonly command?: Endpoint21_1Request["payload"]["command"]
  readonly args?: Endpoint21_1Request["payload"]["args"]
  readonly cwd?: Endpoint21_1Request["payload"]["cwd"]
  readonly title?: Endpoint21_1Request["payload"]["title"]
  readonly env?: Endpoint21_1Request["payload"]["env"]
}
export type Endpoint21_1Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.create"]>>
export type PtyCreateOperation<E = never> = (input?: Endpoint21_1Input) => Effect.Effect<Endpoint21_1Output, E>

type Endpoint21_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
export type Endpoint21_2Input = {
  readonly ptyID: Endpoint21_2Request["params"]["ptyID"]
  readonly location?: Endpoint21_2Request["query"]["location"]
}
export type Endpoint21_2Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.get"]>>
export type PtyGetOperation<E = never> = (input: Endpoint21_2Input) => Effect.Effect<Endpoint21_2Output, E>

type Endpoint21_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
export type Endpoint21_3Input = {
  readonly ptyID: Endpoint21_3Request["params"]["ptyID"]
  readonly location?: Endpoint21_3Request["query"]["location"]
  readonly title?: Endpoint21_3Request["payload"]["title"]
  readonly size?: Endpoint21_3Request["payload"]["size"]
}
export type Endpoint21_3Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.update"]>>
export type PtyUpdateOperation<E = never> = (input: Endpoint21_3Input) => Effect.Effect<Endpoint21_3Output, E>

type Endpoint21_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
export type Endpoint21_4Input = {
  readonly ptyID: Endpoint21_4Request["params"]["ptyID"]
  readonly location?: Endpoint21_4Request["query"]["location"]
}
export type Endpoint21_4Output = EffectValue<ReturnType<RawClient["server.pty"]["pty.remove"]>>
export type PtyRemoveOperation<E = never> = (input: Endpoint21_4Input) => Effect.Effect<Endpoint21_4Output, E>

export interface PtyApi<E = never> {
  readonly list: PtyListOperation<E>
  readonly create: PtyCreateOperation<E>
  readonly get: PtyGetOperation<E>
  readonly update: PtyUpdateOperation<E>
  readonly remove: PtyRemoveOperation<E>
}

type Endpoint22_0Request = Parameters<RawClient["server.shell"]["shell.list"]>[0]
export type Endpoint22_0Input = { readonly location?: Endpoint22_0Request["query"]["location"] }
export type Endpoint22_0Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.list"]>>
export type ShellListOperation<E = never> = (input?: Endpoint22_0Input) => Effect.Effect<Endpoint22_0Output, E>

type Endpoint22_1Request = Parameters<RawClient["server.shell"]["shell.create"]>[0]
export type Endpoint22_1Input = {
  readonly location?: Endpoint22_1Request["query"]["location"]
  readonly command: Endpoint22_1Request["payload"]["command"]
  readonly cwd?: Endpoint22_1Request["payload"]["cwd"]
  readonly timeout: Endpoint22_1Request["payload"]["timeout"]
  readonly metadata?: Endpoint22_1Request["payload"]["metadata"]
}
export type Endpoint22_1Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.create"]>>
export type ShellCreateOperation<E = never> = (input: Endpoint22_1Input) => Effect.Effect<Endpoint22_1Output, E>

type Endpoint22_2Request = Parameters<RawClient["server.shell"]["shell.get"]>[0]
export type Endpoint22_2Input = {
  readonly id: Endpoint22_2Request["params"]["id"]
  readonly location?: Endpoint22_2Request["query"]["location"]
}
export type Endpoint22_2Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.get"]>>
export type ShellGetOperation<E = never> = (input: Endpoint22_2Input) => Effect.Effect<Endpoint22_2Output, E>

type Endpoint22_3Request = Parameters<RawClient["server.shell"]["shell.timeout"]>[0]
export type Endpoint22_3Input = {
  readonly id: Endpoint22_3Request["params"]["id"]
  readonly location?: Endpoint22_3Request["query"]["location"]
  readonly timeout: Endpoint22_3Request["payload"]["timeout"]
}
export type Endpoint22_3Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.timeout"]>>
export type ShellTimeoutOperation<E = never> = (input: Endpoint22_3Input) => Effect.Effect<Endpoint22_3Output, E>

type Endpoint22_4Request = Parameters<RawClient["server.shell"]["shell.output"]>[0]
export type Endpoint22_4Input = {
  readonly id: Endpoint22_4Request["params"]["id"]
  readonly location?: Endpoint22_4Request["query"]["location"]
  readonly cursor?: Endpoint22_4Request["query"]["cursor"]
  readonly limit?: Endpoint22_4Request["query"]["limit"]
}
export type Endpoint22_4Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.output"]>>
export type ShellOutputOperation<E = never> = (input: Endpoint22_4Input) => Effect.Effect<Endpoint22_4Output, E>

type Endpoint22_5Request = Parameters<RawClient["server.shell"]["shell.remove"]>[0]
export type Endpoint22_5Input = {
  readonly id: Endpoint22_5Request["params"]["id"]
  readonly location?: Endpoint22_5Request["query"]["location"]
}
export type Endpoint22_5Output = EffectValue<ReturnType<RawClient["server.shell"]["shell.remove"]>>
export type ShellRemoveOperation<E = never> = (input: Endpoint22_5Input) => Effect.Effect<Endpoint22_5Output, E>

export interface ShellApi<E = never> {
  readonly list: ShellListOperation<E>
  readonly create: ShellCreateOperation<E>
  readonly get: ShellGetOperation<E>
  readonly timeout: ShellTimeoutOperation<E>
  readonly output: ShellOutputOperation<E>
  readonly remove: ShellRemoveOperation<E>
}

type Endpoint23_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
export type Endpoint23_0Input = { readonly location?: Endpoint23_0Request["query"]["location"] }
export type Endpoint23_0Output = EffectValue<ReturnType<RawClient["server.question"]["question.request.list"]>>
export type QuestionRequestListOperation<E = never> = (
  input?: Endpoint23_0Input,
) => Effect.Effect<Endpoint23_0Output, E>

type Endpoint23_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
export type Endpoint23_1Input = { readonly sessionID: Endpoint23_1Request["params"]["sessionID"] }
export type Endpoint23_1Output = EffectValue<ReturnType<RawClient["server.question"]["session.question.list"]>>["data"]
export type QuestionListOperation<E = never> = (input: Endpoint23_1Input) => Effect.Effect<Endpoint23_1Output, E>

type Endpoint23_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
export type Endpoint23_2Input = {
  readonly sessionID: Endpoint23_2Request["params"]["sessionID"]
  readonly requestID: Endpoint23_2Request["params"]["requestID"]
  readonly answers: Endpoint23_2Request["payload"]["answers"]
}
export type Endpoint23_2Output = EffectValue<ReturnType<RawClient["server.question"]["session.question.reply"]>>
export type QuestionReplyOperation<E = never> = (input: Endpoint23_2Input) => Effect.Effect<Endpoint23_2Output, E>

type Endpoint23_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
export type Endpoint23_3Input = {
  readonly sessionID: Endpoint23_3Request["params"]["sessionID"]
  readonly requestID: Endpoint23_3Request["params"]["requestID"]
}
export type Endpoint23_3Output = EffectValue<ReturnType<RawClient["server.question"]["session.question.reject"]>>
export type QuestionRejectOperation<E = never> = (input: Endpoint23_3Input) => Effect.Effect<Endpoint23_3Output, E>

export interface QuestionApi<E = never> {
  readonly request: { readonly list: QuestionRequestListOperation<E> }
  readonly list: QuestionListOperation<E>
  readonly reply: QuestionReplyOperation<E>
  readonly reject: QuestionRejectOperation<E>
}

type Endpoint24_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
export type Endpoint24_0Input = { readonly location?: Endpoint24_0Request["query"]["location"] }
export type Endpoint24_0Output = EffectValue<ReturnType<RawClient["server.reference"]["reference.list"]>>
export type ReferenceListOperation<E = never> = (input?: Endpoint24_0Input) => Effect.Effect<Endpoint24_0Output, E>

export interface ReferenceApi<E = never> {
  readonly list: ReferenceListOperation<E>
}

type Endpoint25_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
export type Endpoint25_0Input = {
  readonly projectID: Endpoint25_0Request["params"]["projectID"]
  readonly location?: Endpoint25_0Request["query"]["location"]
  readonly strategy: Endpoint25_0Request["payload"]["strategy"]
  readonly directory: Endpoint25_0Request["payload"]["directory"]
  readonly name?: Endpoint25_0Request["payload"]["name"]
}
export type Endpoint25_0Output = EffectValue<ReturnType<RawClient["server.projectCopy"]["projectCopy.create"]>>
export type ProjectCopyCreateOperation<E = never> = (input: Endpoint25_0Input) => Effect.Effect<Endpoint25_0Output, E>

type Endpoint25_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
export type Endpoint25_1Input = {
  readonly projectID: Endpoint25_1Request["params"]["projectID"]
  readonly location?: Endpoint25_1Request["query"]["location"]
  readonly directory: Endpoint25_1Request["payload"]["directory"]
  readonly force: Endpoint25_1Request["payload"]["force"]
}
export type Endpoint25_1Output = EffectValue<ReturnType<RawClient["server.projectCopy"]["projectCopy.remove"]>>
export type ProjectCopyRemoveOperation<E = never> = (input: Endpoint25_1Input) => Effect.Effect<Endpoint25_1Output, E>

type Endpoint25_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
export type Endpoint25_2Input = {
  readonly projectID: Endpoint25_2Request["params"]["projectID"]
  readonly location?: Endpoint25_2Request["query"]["location"]
}
export type Endpoint25_2Output = EffectValue<ReturnType<RawClient["server.projectCopy"]["projectCopy.refresh"]>>
export type ProjectCopyRefreshOperation<E = never> = (input: Endpoint25_2Input) => Effect.Effect<Endpoint25_2Output, E>

export interface ProjectCopyApi<E = never> {
  readonly create: ProjectCopyCreateOperation<E>
  readonly remove: ProjectCopyRemoveOperation<E>
  readonly refresh: ProjectCopyRefreshOperation<E>
}

type Endpoint26_0Request = Parameters<RawClient["server.vcs"]["vcs.status"]>[0]
export type Endpoint26_0Input = { readonly location?: Endpoint26_0Request["query"]["location"] }
export type Endpoint26_0Output = EffectValue<ReturnType<RawClient["server.vcs"]["vcs.status"]>>
export type VcsStatusOperation<E = never> = (input?: Endpoint26_0Input) => Effect.Effect<Endpoint26_0Output, E>

type Endpoint26_1Request = Parameters<RawClient["server.vcs"]["vcs.diff"]>[0]
export type Endpoint26_1Input = {
  readonly location?: Endpoint26_1Request["query"]["location"]
  readonly mode: Endpoint26_1Request["query"]["mode"]
  readonly context?: Endpoint26_1Request["query"]["context"]
}
export type Endpoint26_1Output = EffectValue<ReturnType<RawClient["server.vcs"]["vcs.diff"]>>
export type VcsDiffOperation<E = never> = (input: Endpoint26_1Input) => Effect.Effect<Endpoint26_1Output, E>

export interface VcsApi<E = never> {
  readonly status: VcsStatusOperation<E>
  readonly diff: VcsDiffOperation<E>
}

export type Endpoint27_0Output = EffectValue<ReturnType<RawClient["server.debug"]["debug.location"]>>
export type DebugLocationListOperation<E = never> = () => Effect.Effect<Endpoint27_0Output, E>

type Endpoint27_1Request = Parameters<RawClient["server.debug"]["debug.location.evict"]>[0]
export type Endpoint27_1Input = { readonly location?: Endpoint27_1Request["query"]["location"] }
export type Endpoint27_1Output = EffectValue<ReturnType<RawClient["server.debug"]["debug.location.evict"]>>
export type DebugLocationEvictOperation<E = never> = (input?: Endpoint27_1Input) => Effect.Effect<Endpoint27_1Output, E>

export interface DebugApi<E = never> {
  readonly location: { readonly list: DebugLocationListOperation<E>; readonly evict: DebugLocationEvictOperation<E> }
}

export interface AppApi<E = never> {
  readonly health: HealthApi<E>
  readonly server: ServerApi<E>
  readonly pairing: PairingApi<E>
  readonly location: LocationApi<E>
  readonly agent: AgentApi<E>
  readonly plugin: PluginApi<E>
  readonly session: SessionApi<E>
  readonly message: MessageApi<E>
  readonly model: ModelApi<E>
  readonly generate: GenerateApi<E>
  readonly provider: ProviderApi<E>
  readonly integration: IntegrationApi<E>
  readonly mcp: McpApi<E>
  readonly credential: CredentialApi<E>
  readonly project: ProjectApi<E>
  readonly form: FormApi<E>
  readonly permission: PermissionApi<E>
  readonly file: FileApi<E>
  readonly command: CommandApi<E>
  readonly skill: SkillApi<E>
  readonly event: EventApi<E>
  readonly pty: PtyApi<E>
  readonly shell: ShellApi<E>
  readonly question: QuestionApi<E>
  readonly reference: ReferenceApi<E>
  readonly projectCopy: ProjectCopyApi<E>
  readonly vcs: VcsApi<E>
  readonly debug: DebugApi<E>
}
